/* tslint:disable */
/* eslint-disable */
/**
 * Todos API
 * The todos API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTodoDto
 */
export interface CreateTodoDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTodoDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTodoDto
     */
    body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTodoDto
     */
    isCompleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateTodoDto
     */
    due?: string;
}

/**
 * Check if a given object implements the CreateTodoDto interface.
 */
export function instanceOfCreateTodoDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function CreateTodoDtoFromJSON(json: any): CreateTodoDto {
    return CreateTodoDtoFromJSONTyped(json, false);
}

export function CreateTodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTodoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'isCompleted': !exists(json, 'isCompleted') ? undefined : json['isCompleted'],
        'due': !exists(json, 'due') ? undefined : json['due'],
    };
}

export function CreateTodoDtoToJSON(value?: CreateTodoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'body': value.body,
        'isCompleted': value.isCompleted,
        'due': value.due,
    };
}

