/* tslint:disable */
/* eslint-disable */
/**
 * Todos API
 * The todos API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ITodoApiResponse
 */
export interface ITodoApiResponse {
    /**
     * 
     * @type {string}
     * @memberof ITodoApiResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ITodoApiResponse
     */
    body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ITodoApiResponse
     */
    isCompleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof ITodoApiResponse
     */
    due: string;
    /**
     * 
     * @type {string}
     * @memberof ITodoApiResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ITodoApiResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ITodoApiResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the ITodoApiResponse interface.
 */
export function instanceOfITodoApiResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "isCompleted" in value;
    isInstance = isInstance && "due" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function ITodoApiResponseFromJSON(json: any): ITodoApiResponse {
    return ITodoApiResponseFromJSONTyped(json, false);
}

export function ITodoApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ITodoApiResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'isCompleted': json['isCompleted'],
        'due': json['due'],
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function ITodoApiResponseToJSON(value?: ITodoApiResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'body': value.body,
        'isCompleted': value.isCompleted,
        'due': value.due,
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}

