/* tslint:disable */
/* eslint-disable */
/**
 * Todos API
 * The todos API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTodoDto
 */
export interface UpdateTodoDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTodoDto
     */
    isCompleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    due?: string;
}

/**
 * Check if a given object implements the UpdateTodoDto interface.
 */
export function instanceOfUpdateTodoDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTodoDtoFromJSON(json: any): UpdateTodoDto {
    return UpdateTodoDtoFromJSONTyped(json, false);
}

export function UpdateTodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTodoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'isCompleted': !exists(json, 'isCompleted') ? undefined : json['isCompleted'],
        'due': !exists(json, 'due') ? undefined : json['due'],
    };
}

export function UpdateTodoDtoToJSON(value?: UpdateTodoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'body': value.body,
        'isCompleted': value.isCompleted,
        'due': value.due,
    };
}

